### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by k3yavi** [lazappi/phd-thesis#1]
Hi @lazappi ,

Thanks for making your thesis source and analysis public, really enjoyed reading it and congratulations for your defense ! I am thinking of using some of the resources here and was wondering what's the best way to cite your thesis?

**Comment by lazappi** [comment]
There probably isn't a great way to cite it at the moment, I was waiting to see what kind of citation the university creates once it is approved.

If it would be useful I can probably creating a DOI for the GitHub repo using Zenodo?

**Comment by k3yavi** [comment]
doi through zenodo would be great ! Thanks for the help.

**Comment by lazappi** [comment]
Here's a Zenodo entry you can use for now until I get a proper reference https://zenodo.org/record/2673035.

**Comment by k3yavi** [comment]
Thanks Luke .

**Comment by lazappi** [comment]
Here is the university repository if it's any use https://minerva-access.unimelb.edu.au/handle/11343/227091
